### PR TITLE
Add anonymous posting feature to thread notification

### PR DESCRIPTION
**Pull request by abhedanil**
Description
-----------------------------
This pull request addresses the issue of revealing the thread creator's name in email notifications when the thread is posted anonymously. The following changes were made:

 Added an `anonymous` parameter to the `sendMentionEmailNotification` function.
- Modified the `postThread` function to pass the `anonymous` parameter.
- Updated email subject and message to reflect anonymous posting.

### Checklist

- Succesfully run all the tests provided in the contributing.md file

### CODE REVIEW

**Review by shawonibnkamal — CHANGES_REQUESTED** [review]
Thank you very much for working on this! Main concern is replyController is also using this method. Either you need to update replyController or set a default value to the parameter in  sendMentionEmailNotification.

Also, can you please run `npm run prettier-fix` in api folder? There are some formatting issue, prettier should fix them automatically.

**Comment by abhedanil** [comment]
Hi @shawonibnkamal  , by following my method we can avoid a db operation right ?

**Comment by shawonibnkamal** [comment]
> Hi @shawonibnkamal , by following my method we can avoid a db operation right ? In your suggested method we are trying to fetch details without checking the the message is anonymous or not . Correct me if i am wrong .

Good point! Yes, you can do it your way as long as the constant string is defined on top of the file and the formatting issues are fixed.

**Comment by abhedanil** [comment]
I made All the changes you suggested .

### Change Summary

- Implemented logic to ensure anonymous thread submissions do not reveal the sender's name in email notifications.
- Optimized code to avoid unnecessary database operations when the post is anonymous.
- Added `ANONYMOUS_USER` at the top  constant for cleaner code.
- Set default value of `anonymous` to `false` to maintain compatibility with `replyController`.
- Formatting issues are fixed by adding npm run prettier-fix

**Comment by shawonibnkamal** [comment]
Thanks @abhedanil, code tested good! Would you be able to run `npm run prettier-fix` again? The formatting issue does not seem to be fixed, I wonder if prettier is not working as expected.

Also, can you let me know what trouble you are having with the local setup? Your feedback will help improve the local setup.

**Review by shawonibnkamal — APPROVED** [review]
LGTM  ✨ Thank you

**Comment by shawonibnkamal** [comment]
> HI, @shawonibnkamal formatted the code . The local issue i am facing was i couldn't trigger the api edpoint for creating threads.

How were you trying to test it? Did you run the extension and server locally?

**Comment by shawonibnkamal** [comment]
Hi @abhedanil, also noticed your commit isn't connected to your github account. You may want to set it up correctly.

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user

**Comment by abhedanil** [comment]
Can i add a comment in the code  and so it counts on my contribution ?

**Comment by abhedanil** [comment]
Actually i was not able to test the reply and post thread in local because i was not able to trigger api by curl or postman . If you can guide me through the steps i will be able to take other tasks too.

**Comment by shawonibnkamal** [comment]
> Its seems my git config changed somehow. Can i add a comment in the code and so it counts on my contribution?

For sure! You can refactor or clean up any unclean code. We avoid inline comments unless necessary. I should be able to add some easy tasks by the weekend if you're interested.

> Actually i was not able to test the reply and post thread in local because i was not able to trigger api by curl or postman . If you can guide me through the steps i will be able to take other tasks too.

You don't need to use postman. Were you able to run the extension locally? You should be able to test your local server easily using the extension in debugger mode.

**Comment by abhedanil** [comment]
Sure . Please assign some more task if possible , i can take up that. I will try to run the extension next time . Thanks.

**Pull request merged**
